language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
script:
  # Run unit tests from code files
  - ./numbers.py
  - ./datetimes.py

  # Run codestyle checks
  - cd "$TRAVIS_BUILD_DIR"
  - pip install pep8
  - pep8 --config=setup.cfg --statistics -v .
