language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
script:
  # Run unit tests from code files
  - python -m unittest discover -s tests/ -v

  # Run codestyle checks
  - cd "$TRAVIS_BUILD_DIR"
  - pip install pycodestyle
  - pycodestyle --config=setup.cfg --statistics -v .
